
  create table "ops"."crew_members" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "crew_id" bigint not null,
    "profile_id" bigint not null,
    "joined_at" timestamp with time zone not null default now()
      );


alter table "ops"."crews" drop column "crew_type";

CREATE INDEX crew_members_crew_id_idx ON ops.crew_members USING btree (crew_id);

CREATE UNIQUE INDEX crew_members_crew_id_profile_id_idx ON ops.crew_members USING btree (crew_id, profile_id);

CREATE UNIQUE INDEX crew_members_pkey ON ops.crew_members USING btree (id);

CREATE INDEX crew_members_profile_id_idx ON ops.crew_members USING btree (profile_id);

alter table "ops"."crew_members" add constraint "crew_members_pkey" PRIMARY KEY using index "crew_members_pkey";

alter table "ops"."crew_members" add constraint "crew_members.chk_creation_time_not_in_future" CHECK ((created_at <= now())) not valid;

alter table "ops"."crew_members" validate constraint "crew_members.chk_creation_time_not_in_future";

alter table "ops"."crew_members" add constraint "crew_members.chk_update_not_earlier_than_create" CHECK ((updated_at >= created_at)) not valid;

alter table "ops"."crew_members" validate constraint "crew_members.chk_update_not_earlier_than_create";

alter table "ops"."crew_members" add constraint "crew_members_crew_id_fkey" FOREIGN KEY (crew_id) REFERENCES ops.crews(id) ON DELETE CASCADE not valid;

alter table "ops"."crew_members" validate constraint "crew_members_crew_id_fkey";

alter table "ops"."crew_members" add constraint "crew_members_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES iam.profiles(id) ON DELETE CASCADE not valid;

alter table "ops"."crew_members" validate constraint "crew_members_profile_id_fkey";


